version: '3'
services:
  db:
    container_name: wordpress-db
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - wordpress-db:/var/lib/mysql
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ''
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
volumes:
  wordpress-db:
